# Generated by Django 3.0.5 on 2023-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('student_username', models.CharField(max_length=100)),
            ],
        ),
    ]
